# Uncomment the next line to define a global platform for your project
platform :ios, '14.0'

target 'SkifTest' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SkifTest
  pod 'GoogleMaps', '8.3.0'
end
